// Copyright (C) 2026 NebulaAPU contributors
// SPDX-License-Identifier: GPL-2.0-only

using System.Globalization;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Ps5Recomp.Cli;

internal static class RuntimeMetadataGenerator
{
    public static (string HeaderPath, string SourcePath) Generate(
        string packageDirectory)
    {
        var fullPackageDirectory = Path.GetFullPath(packageDirectory);
        var generatedDirectory = Path.Combine(fullPackageDirectory, "generated");
        var headerPath = Path.Combine(generatedDirectory, "runtime_guest_image.h");
        var sourcePath = Path.Combine(generatedDirectory, "runtime_guest_image.cpp");
        var images = LoadImages(fullPackageDirectory);
        var main = images[0].Manifest;
        if (main.FormatVersion <= 0 ||
            main.EntryPoint == 0 ||
            main.Segments.Count == 0)
        {
            throw new InvalidDataException(
                "Static package manifest lacks runtime mapping metadata.");
        }

        Directory.CreateDirectory(generatedDirectory);
        File.WriteAllText(
            headerPath,
            CreateHeader(main, images),
            new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        File.WriteAllText(
            sourcePath,
            CreateSource(images),
            new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        return (headerPath, sourcePath);
    }

    private static List<RuntimeImage> LoadImages(string packageDirectory)
    {
        var images = new List<RuntimeImage>
        {
            LoadImage(packageDirectory, packageDirectory),
        };
        var modulesDirectory = Path.Combine(packageDirectory, "modules");
        if (!Directory.Exists(modulesDirectory))
        {
            return images;
        }

        foreach (var manifestPath in Directory
                     .EnumerateFiles(
                         modulesDirectory,
                         "manifest.json",
                         SearchOption.AllDirectories)
                     .OrderBy(path => path, StringComparer.OrdinalIgnoreCase))
        {
            images.Add(LoadImage(
                packageDirectory,
                Path.GetDirectoryName(manifestPath)!));
        }
        return images;
    }

    private static RuntimeImage LoadImage(
        string packageDirectory,
        string imageDirectory)
    {
        var manifestPath = Path.Combine(imageDirectory, "manifest.json");
        var imagePath = Path.Combine(imageDirectory, "image.bin");
        if (!File.Exists(manifestPath))
        {
            throw new FileNotFoundException(
                "Static package manifest was not found.",
                manifestPath);
        }
        if (!File.Exists(imagePath))
        {
            throw new FileNotFoundException(
                "Static package memory image was not found.",
                imagePath);
        }

        using var stream = File.OpenRead(manifestPath);
        var manifest = JsonSerializer.Deserialize<RuntimeManifest>(stream) ??
            throw new InvalidDataException(
                $"Static package manifest is empty: {manifestPath}");
        var relativeImagePath = Path
            .GetRelativePath(packageDirectory, imagePath)
            .Replace('\\', '/');
        return new RuntimeImage(relativeImagePath, manifest);
    }

    private static string CreateHeader(
        RuntimeManifest main,
        IReadOnlyList<RuntimeImage> images)
    {
        var segmentCount = images.Sum(image => image.Manifest.Segments.Count);
        var importCount = images.Sum(image => image.Manifest.Imports.Count);
        var symbolCount = GetRequiredRuntimeSymbols(images).Count;
        var relocationCount = images.Sum(
            image => image.Manifest.ImportedRelocations.Count);
        var initializerCount = GetModuleInitializers(images).Count;
        var tlsModules = GetTlsModules(images);

        var text = new StringBuilder();
        text.AppendLine("// Generated by ps5recomp. Do not edit.");
        text.AppendLine("#pragma once");
        text.AppendLine();
        text.AppendLine("#include <array>");
        text.AppendLine("#include <cstddef>");
        text.AppendLine("#include <cstdint>");
        text.AppendLine();
        text.AppendLine("namespace sharprecomp::generated {");
        text.AppendLine();
        text.AppendLine("struct ImageDescriptor {");
        text.AppendLine("    const char* relative_path;");
        text.AppendLine("};");
        text.AppendLine();
        text.AppendLine("struct SegmentDescriptor {");
        text.AppendLine("    std::uint64_t virtual_address;");
        text.AppendLine("    std::uint64_t memory_size;");
        text.AppendLine("    std::uint64_t blob_offset;");
        text.AppendLine("    std::uint32_t protection;");
        text.AppendLine("    std::uint32_t image_index;");
        text.AppendLine("};");
        text.AppendLine();
        text.AppendLine("struct ImportDescriptor {");
        text.AppendLine("    std::uint64_t stub_address;");
        text.AppendLine("    const char* nid;");
        text.AppendLine("};");
        text.AppendLine();
        text.AppendLine("struct RuntimeSymbolDescriptor {");
        text.AppendLine("    const char* nid;");
        text.AppendLine("    std::uint64_t address;");
        text.AppendLine("};");
        text.AppendLine();
        text.AppendLine("struct ImportedRelocationDescriptor {");
        text.AppendLine("    std::uint64_t target_address;");
        text.AppendLine("    std::int64_t addend;");
        text.AppendLine("    const char* nid;");
        text.AppendLine("    bool is_data;");
        text.AppendLine("};");
        text.AppendLine();
        text.AppendLine("struct InitializerDescriptor {");
        text.AppendLine("    std::uint64_t address;");
        text.AppendLine("    const char* image_name;");
        text.AppendLine("};");
        text.AppendLine();
        text.AppendLine("struct TlsModuleDescriptor {");
        text.AppendLine("    std::uint64_t module_id;");
        text.AppendLine("    std::uint64_t memory_size;");
        text.AppendLine("    std::uint64_t static_offset;");
        text.AppendLine("    std::uint64_t init_address;");
        text.AppendLine("    std::uint64_t init_size;");
        text.AppendLine("};");
        text.AppendLine();
        text.AppendLine(
            $"inline constexpr std::uint32_t kManifestFormatVersion = {main.FormatVersion}U;");
        text.AppendLine(
            $"inline constexpr std::uint64_t kImageBase = {Hex(main.ImageBase)};");
        text.AppendLine(
            $"inline constexpr std::uint64_t kEntryPoint = {Hex(main.EntryPoint)};");
        text.AppendLine(
            $"inline constexpr std::uint64_t kProcParamAddress = {Hex(main.ProcParamAddress)};");
        text.AppendLine(
            $"inline constexpr std::size_t kImageCount = {images.Count};");
        text.AppendLine(
            $"inline constexpr std::size_t kSegmentCount = {segmentCount};");
        text.AppendLine(
            $"inline constexpr std::size_t kImportCount = {importCount};");
        text.AppendLine(
            $"inline constexpr std::size_t kRuntimeSymbolCount = {symbolCount};");
        text.AppendLine(
            $"inline constexpr std::size_t kImportedRelocationCount = {relocationCount};");
        text.AppendLine(
            $"inline constexpr std::size_t kInitializerCount = {initializerCount};");
        text.AppendLine(
            $"inline constexpr std::size_t kTlsModuleCount = {tlsModules.Count};");
        text.AppendLine();
        text.AppendLine(
            "extern const std::array<ImageDescriptor, kImageCount> kImages;");
        text.AppendLine(
            "extern const std::array<SegmentDescriptor, kSegmentCount> kSegments;");
        text.AppendLine(
            "extern const std::array<ImportDescriptor, kImportCount> kImports;");
        text.AppendLine(
            "extern const std::array<RuntimeSymbolDescriptor, kRuntimeSymbolCount> kRuntimeSymbols;");
        text.AppendLine(
            "extern const std::array<ImportedRelocationDescriptor, kImportedRelocationCount> kImportedRelocations;");
        text.AppendLine(
            "extern const std::array<InitializerDescriptor, kInitializerCount> kInitializers;");
        text.AppendLine(
            "extern const std::array<TlsModuleDescriptor, kTlsModuleCount> kTlsModules;");
        text.AppendLine();
        text.AppendLine("} // namespace sharprecomp::generated");
        return text.ToString();
    }

    private static string CreateSource(IReadOnlyList<RuntimeImage> images)
    {
        var text = new StringBuilder();
        text.AppendLine("// Generated by ps5recomp. Do not edit.");
        text.AppendLine("#include \"runtime_guest_image.h\"");
        text.AppendLine();
        text.AppendLine("namespace sharprecomp::generated {");
        text.AppendLine();
        text.AppendLine(
            "const std::array<ImageDescriptor, kImageCount> kImages = {{");
        foreach (var image in images)
        {
            text.Append("    { \"")
                .Append(EscapeCppString(image.RelativePath))
                .AppendLine("\" },");
        }
        text.AppendLine("}};");
        text.AppendLine();
        text.AppendLine(
            "const std::array<SegmentDescriptor, kSegmentCount> kSegments = {{");
        for (var imageIndex = 0; imageIndex < images.Count; imageIndex++)
        {
            foreach (var segment in images[imageIndex].Manifest.Segments)
            {
                text.Append("    { ")
                    .Append(Hex(segment.VirtualAddress)).Append(", ")
                    .Append(Hex(segment.MemorySize)).Append(", ")
                    .Append(Hex(segment.BlobOffset)).Append(", 0x")
                    .Append(segment.Protection.ToString(
                        "X",
                        CultureInfo.InvariantCulture))
                    .Append("U, ")
                    .Append(imageIndex)
                    .AppendLine("U },");
            }
        }
        text.AppendLine("}};");
        text.AppendLine();
        text.AppendLine(
            "const std::array<ImportDescriptor, kImportCount> kImports = {{");
        foreach (var import in images.SelectMany(image => image.Manifest.Imports))
        {
            text.Append("    { ")
                .Append(Hex(import.StubAddress))
                .Append(", \"")
                .Append(EscapeCppString(import.Nid))
                .AppendLine("\" },");
        }
        text.AppendLine("}};");
        text.AppendLine();
        text.AppendLine(
            "const std::array<RuntimeSymbolDescriptor, kRuntimeSymbolCount> kRuntimeSymbols = {{");
        foreach (var symbol in GetRequiredRuntimeSymbols(images))
        {
            text.Append("    { \"")
                .Append(EscapeCppString(symbol.Name))
                .Append("\", ")
                .Append(Hex(symbol.Address))
                .AppendLine(" },");
        }
        text.AppendLine("}};");
        text.AppendLine();
        text.AppendLine(
            "const std::array<ImportedRelocationDescriptor, kImportedRelocationCount> kImportedRelocations = {{");
        foreach (var relocation in images.SelectMany(
                     image => image.Manifest.ImportedRelocations))
        {
            text.Append("    { ")
                .Append(Hex(relocation.TargetAddress))
                .Append(", ")
                .Append(relocation.Addend.ToString(CultureInfo.InvariantCulture))
                .Append("LL, \"")
                .Append(EscapeCppString(relocation.Nid))
                .Append("\", ")
                .Append(relocation.IsData ? "true" : "false")
                .AppendLine(" },");
        }
        text.AppendLine("}};");
        text.AppendLine();
        text.AppendLine(
            "const std::array<InitializerDescriptor, kInitializerCount> kInitializers = {{");
        foreach (var initializer in GetModuleInitializers(images))
        {
            text.Append("    { ")
                .Append(Hex(initializer.Address))
                .Append(", \"")
                .Append(EscapeCppString(initializer.ImageName))
                .AppendLine("\" },");
        }
        text.AppendLine("}};");
        text.AppendLine();
        text.AppendLine(
            "const std::array<TlsModuleDescriptor, kTlsModuleCount> kTlsModules = {{");
        foreach (var module in GetTlsModules(images))
        {
            text.Append("    { ")
                .Append(module.ModuleId).Append("ULL, ")
                .Append(Hex(module.MemorySize)).Append(", ")
                .Append(Hex(module.StaticOffset)).Append(", ")
                .Append(Hex(module.InitAddress)).Append(", ")
                .Append(Hex(module.InitSize))
                .AppendLine(" },");
        }
        text.AppendLine("}};");
        text.AppendLine();
        text.AppendLine("} // namespace sharprecomp::generated");
        return text.ToString();
    }

    private static IReadOnlyList<RuntimeSymbol> GetRequiredRuntimeSymbols(
        IReadOnlyList<RuntimeImage> images)
    {
        var requiredNids = images
            .SelectMany(image =>
                image.Manifest.Imports.Select(import => import.Nid)
                    .Concat(image.Manifest.ImportedRelocations.Select(
                        relocation => relocation.Nid)))
            .ToHashSet(StringComparer.Ordinal);
        return images
            .SelectMany(image => image.Manifest.RuntimeSymbols)
            .Where(symbol => requiredNids.Contains(symbol.Name))
            .GroupBy(symbol => symbol.Name, StringComparer.Ordinal)
            .Select(group => group.First())
            .OrderBy(symbol => symbol.Name, StringComparer.Ordinal)
            .ToArray();
    }

    private static IReadOnlyList<RuntimeTlsModule> GetTlsModules(
        IReadOnlyList<RuntimeImage> images)
    {
        var modules = new List<RuntimeTlsModule>();
        foreach (var image in images
                     .Where(image => image.Manifest.TlsModuleId != 0)
                     .OrderBy(image => image.Manifest.TlsModuleId))
        {
            var header = image.Manifest.ProgramHeaders.FirstOrDefault(
                header => header.Type == 7 && header.MemorySize != 0);
            if (header is null)
            {
                throw new InvalidDataException(
                    $"{image.Manifest.SourceFile} has TLS metadata without PT_TLS.");
            }
            modules.Add(new RuntimeTlsModule(
                image.Manifest.TlsModuleId,
                image.Manifest.TlsMemorySize,
                image.Manifest.TlsStaticOffset,
                checked(image.Manifest.ImageBase + header.VirtualAddress),
                Math.Min(header.FileSize, header.MemorySize)));
        }
        return modules;
    }

    private static IReadOnlyList<RuntimeInitializer> GetModuleInitializers(
        IReadOnlyList<RuntimeImage> images) =>
        images
            .Skip(1)
            .SelectMany(image =>
                image.Manifest.InitializerFunctions.Select(address =>
                    new RuntimeInitializer(
                        address,
                        image.Manifest.SourceFile)))
            .ToArray();

    private static string Hex(ulong value) =>
        $"0x{value:X16}ULL";

    private static string EscapeCppString(string value)
    {
        var escaped = new StringBuilder(value.Length);
        foreach (var character in value)
        {
            switch (character)
            {
                case '\\':
                    escaped.Append("\\\\");
                    break;
                case '"':
                    escaped.Append("\\\"");
                    break;
                case '\n':
                    escaped.Append("\\n");
                    break;
                case '\r':
                    escaped.Append("\\r");
                    break;
                case '\t':
                    escaped.Append("\\t");
                    break;
                default:
                    escaped.Append(character);
                    break;
            }
        }
        return escaped.ToString();
    }

    private sealed record RuntimeImage(
        string RelativePath,
        RuntimeManifest Manifest);

    private sealed record RuntimeTlsModule(
        uint ModuleId,
        ulong MemorySize,
        ulong StaticOffset,
        ulong InitAddress,
        ulong InitSize);

    private sealed record RuntimeInitializer(
        ulong Address,
        string ImageName);

    private sealed class RuntimeManifest
    {
        [JsonPropertyName("formatVersion")]
        public int FormatVersion { get; init; }

        [JsonPropertyName("sourceFile")]
        public string SourceFile { get; init; } = string.Empty;

        [JsonPropertyName("imageBase")]
        public ulong ImageBase { get; init; }

        [JsonPropertyName("entryPoint")]
        public ulong EntryPoint { get; init; }

        [JsonPropertyName("procParamAddress")]
        public ulong ProcParamAddress { get; init; }

        [JsonPropertyName("tlsModuleId")]
        public uint TlsModuleId { get; init; }

        [JsonPropertyName("tlsMemorySize")]
        public ulong TlsMemorySize { get; init; }

        [JsonPropertyName("tlsStaticOffset")]
        public ulong TlsStaticOffset { get; init; }

        [JsonPropertyName("programHeaders")]
        public List<RuntimeProgramHeader> ProgramHeaders { get; init; } = [];

        [JsonPropertyName("segments")]
        public List<RuntimeSegment> Segments { get; init; } = [];

        [JsonPropertyName("imports")]
        public List<RuntimeImport> Imports { get; init; } = [];

        [JsonPropertyName("runtimeSymbols")]
        public List<RuntimeSymbol> RuntimeSymbols { get; init; } = [];

        [JsonPropertyName("importedRelocations")]
        public List<RuntimeRelocation> ImportedRelocations { get; init; } = [];

        [JsonPropertyName("preInitializerFunctions")]
        public List<ulong> PreInitializerFunctions { get; init; } = [];

        [JsonPropertyName("initializerFunctions")]
        public List<ulong> InitializerFunctions { get; init; } = [];
    }

    private sealed class RuntimeProgramHeader
    {
        [JsonPropertyName("type")]
        public uint Type { get; init; }

        [JsonPropertyName("virtualAddress")]
        public ulong VirtualAddress { get; init; }

        [JsonPropertyName("fileSize")]
        public ulong FileSize { get; init; }

        [JsonPropertyName("memorySize")]
        public ulong MemorySize { get; init; }
    }

    private sealed class RuntimeSegment
    {
        [JsonPropertyName("virtualAddress")]
        public ulong VirtualAddress { get; init; }

        [JsonPropertyName("memorySize")]
        public ulong MemorySize { get; init; }

        [JsonPropertyName("blobOffset")]
        public ulong BlobOffset { get; init; }

        [JsonPropertyName("protection")]
        public uint Protection { get; init; }
    }

    private sealed class RuntimeImport
    {
        [JsonPropertyName("stubAddress")]
        public ulong StubAddress { get; init; }

        [JsonPropertyName("nid")]
        public string Nid { get; init; } = string.Empty;
    }

    private sealed class RuntimeSymbol
    {
        [JsonPropertyName("name")]
        public string Name { get; init; } = string.Empty;

        [JsonPropertyName("address")]
        public ulong Address { get; init; }
    }

    private sealed class RuntimeRelocation
    {
        [JsonPropertyName("targetAddress")]
        public ulong TargetAddress { get; init; }

        [JsonPropertyName("addend")]
        public long Addend { get; init; }

        [JsonPropertyName("nid")]
        public string Nid { get; init; } = string.Empty;

        [JsonPropertyName("isData")]
        public bool IsData { get; init; }
    }
}
